FROM rust:1.45.2
# needed if your vpn is modifying certs
COPY vpn-ca.pem /usr/local/share/ca-certificates/vpn-ca.crt
RUN chmod 644 /usr/local/share/ca-certificates/vpn-ca.crt && update-ca-certificates
RUN rustup toolchain install nightly && rustup target add wasm32-unknown-unknown --toolchain nightly
WORKDIR /usr/src/app/
COPY . .
RUN cargo +nightly build --target=wasm32-unknown-unknown --release 
