version: '2'
services:

  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/envoy_filter_render_page.wasm:/etc/envoy_filter_render_page.wasm
      # Uncomment this line if you want to use your own Envoy with WASM enabled.
  #    - ./envoy/istio/envoy:/usr/local/bin/envoy
    expose:
      - "8080"
      - "8081"
      - "9901"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9901:9901"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Welcome to WASM land"'
    expose:
      - "5678"
    ports:
      - "18080:5678"
